<?php
/**
 * Yireo IdentificationRequired for Magento
 *
 * @package     Yireo_IdentificationRequired
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2012 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */

$form = $this->getForm();
$customer = $this->getCustomer();
$customerData = $this->getCustomerData();
?>

<div id="customer_info_tabs_customer_edit_tab_action_content">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Customer Information'); ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <tbody>
                <tr>
                    <td class="label"><?php echo $this->__('Date Of Birth'); ?></td>
                    <td class="value"><?php echo $this->getCustomerDateOfBirth(); ?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Current age'); ?></td>
                    <td class="value"><?php echo $this->getCustomerAge(); ?></td>
                </tr>
            </tbody>
            </table>
        </div>
    </div>
    <?php foreach($form->getFieldsets() as $fieldset) : ?>
        <?php echo Mage::helper('formapi/template')->getFieldsetBlock($fieldset); ?>
    <?php endforeach; ?>
</div>
