<?php

/**
 * Yireo IdentificationRequired
 *
 * @package     Yireo_IdentificationRequired
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright 2016 Yireo (https://www.yireo.com/)
 * @license     Open Source License (OSL v3)
 */
class Yireo_IdentificationRequired_Block_Frontend_Checkout_Warning extends Mage_Core_Block_Template
{
    /**
     * Listing of products for which identification is required
     *
     * @var array
     */
    protected $productsIdentificationRequired = array();

    /**
     * Constructor method
     */
    public function _construct()
    {
        parent::_construct();
        $this->setTemplate('identificationrequired/checkout/warning.phtml');
    }

    /**
     * Check whether there is a product that requires identification
     *
     * @return bool
     */
    public function isProductWithIdentificationRequired()
    {
        $this->productsIdentificationRequired = Mage::helper('identificationrequired')->getCartProductsWithIdentificationRequired();

        return (count($this->productsIdentificationRequired) > 0) ? true : false;
    }

    /**
     * Gather all the notices generated by rules
     *
     * @return array
     */
    public function getRuleNotices()
    {
        $ruleNotices = array();

        $cartItems = Mage::getSingleton('checkout/cart')->getItems();

        /** @var Mage_Sales_Model_Order_Item $cartItem */
        foreach ($cartItems as $cartItem) {

            $product = $cartItem->getProduct();
            $rules = Mage::helper('identificationrequired')->getRulesByProduct($product);

            if (!empty($rules)) {
                /** @var Yireo_IdentificationRequired_Model_Rule $rule */
                foreach ($rules as $rule) {
                    if ($rule->getShowCheckoutNotice() == 1) {
                        $productCount = count($rule->getProducts());
                        $ruleNotice = $rule->getCheckoutNotice();
                        $ruleNotice = str_replace('%s', $rule->getProduct(), $ruleNotice);
                        $ruleNotice = str_replace('%d', $productCount, $ruleNotice);
                        if (!in_array($ruleNotice, $ruleNotices)) {
                            $ruleNotices[] = $ruleNotice;
                        }
                    }
                }
            }
        }

        return $ruleNotices;
    }
}
